AWSTemplateFormatVersion: "2010-09-09"
Description: "VPC sample"

Parameters:
  VPCCiderBlock:
    Type: String
    Default: "10.1.0.0./16"
  TagName:
    Type: String
    Default: "vpc"
    Description: "Tag Name"

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCiderBlock
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Ref TagName

Outputs:
  VpcId:
    Description: "VPC ID"
    Value: !Ref VPC
