AWSTemplateFormatVersion: "2010-09-09"
Description: "Public Subnet sample"

Parameters:
  AZ:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: "ap-northeast-1a"
  SubnetPublicCider:
    Type: String
    Default: "10.1.2.0/24"
  SubnetPublicDestinationCidr:
    Type: String
    Default: "0.0.0.0/0"
  TagName:
    Type: String
    Default: "public-subnet"
    Description: "Tag Name"
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "VPC ID"

Resources:
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZ
      CidrBlock: !Ref SubnetPublicCider
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Ref TagName

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Ref TagName

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref TagName

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VpcId

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: !Ref SubnetPublicDestinationCidr
      GatewayId: !Ref InternetGateway

  PublicSubnetTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet

Outputs:
  SubnetID:
    Description: "Subnet ID"
    Value: !Ref PublicSubnet
